version: 2
updates:
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
      timezone: Asia/Calcutta
    open-pull-requests-limit: 5
    target-branch: main
    reviewers:
      - Anilds123
    assignees:
      - Anilds123
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
    open-pull-requests-limit: 5
    target-branch: main
    reviewers:
      - Anilds123
    assignees:
      - Anilds123
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope