on:
  create:

name: Transition Issue To Development

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'create' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/heads/ZPV-') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      
      - name: Find Branch name
        id: find-branch-name
        run: echo "${{ github.ref }}"

      - name: Find in Branch
        id: find-issue-key
        uses: atlassian/gajira-find-issue-key@v2.0.2
        with:
          string: ${{ github.ref }}

      - name: Jira Issue Ticket
        run: echo "Issue ${{ steps.find-issue-key.outputs.issue }}"

      - name: Jira Issue Transition
        uses: atlassian/gajira-transition@v2.0.2
        with:
          issue: ${{ steps.find-issue-key.outputs.issue }}
          transition: ${{ secrets.JIRA_IN_DEVELOPMENT_TRANS }}